### ISSUE TITLE
Add language to FAQ explaining why ARPA SLFRF spending zip codes outside chicago

### ISSUE THREAD

**Issue by alenastern** [Chi-Trust/Stg-Recovery-Funds-Dashboard#1]

**Comment by kramosurban** [comment]
Proposed language based on notes from our April 22 Trust meeting:

In some cases, zip codes in the table are from communities outside of Chicago, Cook County, and Illinois. Businesses with zip codes outside of these jurisdictions may have an operating or headquarters address in another zip code but provide specific services in Chicago, Cook County, and Illinois.
