### ISSUE TITLE
Gap in Allocations vs. Budget Chart Footnote

### ISSUE THREAD

**Issue by kramosurban** [Chi-Trust/Stg-Recovery-Funds-Dashboard#25]
Update footnote to remove the first blurb and only read:

**Note:** Negative values indicate that local governments’ total adopted budgets for the given topic across all individual programs were lower than their original allocated amounts. Capacity building programs do not appear in this chart because original allocation amounts for capacity building were not specifically enumerated in the Covid-19 economic recovery plans referenced in this dashboard.

**Comment by rpitingolo** [comment]
Updated this and other text edits from the Boxnote.
