### ISSUE TITLE
make updates to ARPA SLFRF spending by quarter chart

### ISSUE THREAD

**Issue by alenastern** [Chi-Trust/Stg-Recovery-Funds-Dashboard#7]
- [ ] update chart to show cumulative spending as a percentage of adopted budget by quarter (should monotonically increase over time)
- [ ] make chart vertically shorter so chart and title fit within screen 
- [ ] Change colors to Trust branding

**Comment by rpitingolo** [comment]
@alenastern can you please paste a screenshot of the chart in question? Is it just one chart or several under the tabs?

**Comment by rpitingolo** [comment]
Spending by quarter is now incorporated.
