### ISSUE TITLE
remove `library(sknifedatar)` from dashboard

### ISSUE THREAD

**Issue by alenastern** [Chi-Trust/Stg-Recovery-Funds-Dashboard#9]
Currently we dynamically generate a couple sets of tabs using `library(sknifedatar)` and `xaringanExtra::use_panelset()`

It seems that  `library(sknifedatar)`  has been removed from CRAN and I get an error when I try to install form github. We either need to resolve the installation issue, or use an alternate approach - whether that's manually creating the chunks or using the alternate dynamic chunk approach in #8

**Comment by rpitingolo** [comment]
I think this one is complete as the code no longer uses `sknifedatar`
